apiVersion : v1
kind: ConfigMap
metadata:
  name: ghost-config
data:
  index.html: |
    <html >
    <head ><title >NGINX </title ></head >
    <body ><h1 >Witamy na serwerze NGINX </h1 ></body >
    </html >
